apiVersion: v1
kind: Service
metadata:
  name: hello-node-lb-service
spec:
  ports:
  - port: 80
    targetPort: nodejs-port # must be the same as described in the pod file
    protocol: TCP
  selector:
    app: hello-node # refers to the pod's label app: <name>
  type: LoadBalancer
