apiVersion: v1
kind: Pod
metadata:
  name: hello-node.example.com
  labels:
    app: hello-node
spec:
  containers:
    - name: kubernetes-hello-node-app
      image: devkaoru/kubernetes_hello_node_app
      ports:
        - containerPort: 3000
